// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxvunutxnwibrgkbdghk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4dnVudXR4bndpYnJna2JkZ2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDQ3MDAsImV4cCI6MjA3NDI4MDcwMH0.AO8C965RaM2ACSOPM-yspTFBdkpyp9snQBrnqYiEaRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});